In [11]:
import pandas as pd

#### **Creating Two Separate Files for Newly Listed and Sold Properties**

##### Newly Listed Properties

In [117]:
'''
This code reads multiple CSV files containing real estate listings
df_list = []
for i in range(2024, 2027):
    stop_condition = False
    for j in range(1, 13):
        file_path = f"../data/Listing/CRMLSListing{i}{j:02d}.csv"
        
        if i == 2026 and j == 4:
            stop_condition = True
            break
        print(f"Reading file: {file_path}")
        df_listing = pd.read_csv(file_path, encoding="ISO-8859-1")
        df_list.append(df_listing)
    if stop_condition:
        break
df_listings = pd.concat(df_list, ignore_index=True)
'''

'\nThis code reads multiple CSV files containing real estate listings\ndf_list = []\nfor i in range(2024, 2027):\n    stop_condition = False\n    for j in range(1, 13):\n        file_path = f"../data/Listing/CRMLSListing{i}{j:02d}.csv"\n\n        if i == 2026 and j == 4:\n            stop_condition = True\n            break\n        print(f"Reading file: {file_path}")\n        df_listing = pd.read_csv(file_path, encoding="ISO-8859-1")\n        df_list.append(df_listing)\n    if stop_condition:\n        break\ndf_listings = pd.concat(df_list, ignore_index=True)\n'

In [ ]:
# df_listings.to_csv("../data/Listing/listed_transactions.csv", index=False)

In [13]:
df_listings = pd.read_csv("../data/Listing/listed_transactions.csv", encoding="ISO-8859-1")
df_listings.head()

C:\Users\mayab\AppData\Local\Temp\ipykernel_18104\974492464.py:1: DtypeWarning: Columns (0: ListAgentEmail, 1: BuyerAgencyCompensationType) have mixed types. Specify dtype option on import or set low_memory=False.
  df_listings = pd.read_csv("../data/Listing/listed_transactions.csv", encoding="ISO-8859-1")

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,90000.0,1075010398,miriamlara03@gmail.com,NaN,NaN,Miriam,Lara,34.097939,-117.909653,1045 N Azusa 61,...,NaN,NaN,2.0,Covina Valley Unified,91722,NaN,0.0,NaN,NaN,1045 N Azusa 61
1,1500000.0,1074974457,janelle@judsonre.com,NaN,NaN,Janelle,Judson,33.121241,-117.081614,NaN,...,NaN,NaN,NaN,NaN,92025,NaN,0.0,NaN,NaN,NaN
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,False,NaN,NaN,90067,NaN,2105.0,177861.0,NaN,2220 Avenue Of The Stars 2704
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,0.0,False,3.0,Capistrano Unified,92677,NaN,254.0,5300.0,NaN,16 Palisades
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road

In [14]:
df_listings.shape

(853754, 84)

##### Closed/Sold Properties

In [8]:
'''
This code reads multiple CSV files containing real estate sold listings
df_sold = []
for i in range(2024, 2027):
    stop_condition = False
    for j in range(1, 13):
        file_path = f"../data/Sold/CRMLSSold{i}{j:02d}.csv"
        
        if i == 2026 and j == 4:
            stop_condition = True
            break
        print(f"Reading file: {file_path}")
        df_sold.append(df_sold)
    if stop_condition:
        break
df_sold_listings = pd.concat(df_sold, ignore_index=True)
'''

'\nThis code reads multiple CSV files containing real estate sold listings\ndf_sold = []\nfor i in range(2024, 2027):\n    stop_condition = False\n    for j in range(1, 13):\n        file_path = f"../data/Sold/CRMLSSold{i}{j:02d}.csv"\n\n        if i == 2026 and j == 4:\n            stop_condition = True\n            break\n        print(f"Reading file: {file_path}")\n        df_sold.append(df_sold)\n    if stop_condition:\n        break\ndf_sold_listings = pd.concat(df_sold, ignore_index=True)\n'

In [ ]:
# df_sold_listings.to_csv("../data/Sold/sold_transactions.csv", index=False)

In [16]:
df_sold_listings = pd.read_csv("../data/Sold/sold_transactions.csv", encoding="ISO-8859-1")
df_sold_listings.head()

C:\Users\mayab\AppData\Local\Temp\ipykernel_18104\2392212637.py:1: DtypeWarning: Columns (0: BuyerAgentAOR, 1: ListAgentAOR, 2: WaterfrontYN, 3: ListAgentEmail, 4: OriginatingSystemName, 5: OriginatingSystemSubName, 6: BuyerAgencyCompensationType, 7: latfilled, 8: lonfilled) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sold_listings = pd.read_csv("../data/Sold/sold_transactions.csv", encoding="ISO-8859-1")

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,94401,6472.0,NaN,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN
1,HighDesert,HighDesert,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,...,92394,NaN,52320.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
2,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,...,93240,NaN,217364.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
3,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,...,92308,NaN,217800.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,...,93544,0.0,108883.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN

In [17]:
df_sold_listings.shape

(591115, 84)