In [1]:
import pandas as pd

### Listed Properties

In [2]:
df_listing = pd.read_csv("../data/Listing/listed_transactions.csv", encoding="ISO-8859-1")

C:\Users\mayab\AppData\Local\Temp\ipykernel_11692\2095627017.py:1: DtypeWarning: Columns (0: ListAgentEmail, 1: BuyerAgencyCompensationType) have mixed types. Specify dtype option on import or set low_memory=False.
  df_listing = pd.read_csv("../data/Listing/listed_transactions.csv", encoding="ISO-8859-1")

In [3]:
df_listing.head()

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1,Year
0,90000.0,1075010398,miriamlara03@gmail.com,NaN,NaN,Miriam,Lara,34.097939,-117.909653,1045 N Azusa 61,...,NaN,2.0,Covina Valley Unified,91722,NaN,0.0,NaN,NaN,1045 N Azusa 61,2024
1,1500000.0,1074974457,janelle@judsonre.com,NaN,NaN,Janelle,Judson,33.121241,-117.081614,NaN,...,NaN,NaN,NaN,92025,NaN,0.0,NaN,NaN,NaN,2024
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,False,NaN,NaN,90067,NaN,2105.0,177861.0,NaN,2220 Avenue Of The Stars 2704,2024
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,False,3.0,Capistrano Unified,92677,NaN,254.0,5300.0,NaN,16 Palisades,2024
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road,2024

In [4]:
df_listing.columns

Index(['OriginalListPrice', 'ListingKey', 'ListAgentEmail', 'CloseDate',
       'ClosePrice', 'ListAgentFirstName', 'ListAgentLastName', 'Latitude',
       'Longitude', 'UnparsedAddress', 'PropertyType', 'LivingArea',
       'ListPrice', 'DaysOnMarket', 'ListOfficeName', 'BuyerOfficeName',
       'CoListOfficeName', 'ListAgentFullName', 'CoListAgentFirstName',
       'CoListAgentLastName', 'BuyerAgentMlsId', 'BuyerAgentFirstName',
       'BuyerAgentLastName', 'FireplacesTotal', 'AssociationFeeFrequency',
       'AboveGradeFinishedArea', 'ListingKeyNumeric', 'MLSAreaMajor',
       'TaxAnnualAmount', 'CountyOrParish', 'PropertyType.1', 'MlsStatus',
       'ElementarySchool', 'ListAgentFirstName.1', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'DaysOnMarket.1',
       'BuyerAgencyCompensationType', 'StreetNumberNumeric', 'LivingArea.1',
       'ListingId', 'BathroomsTotalInteger', 'City', 'BuyerAgencyCompensation',
       'TaxYear', 'BuildingAreaTotal', 'BedroomsTotal',
       'ContractStatusChangeDate', 'Longitude.1', 'ElementarySchoolDistrict',
       'CoBuyerAgentFirstName', 'PurchaseContractDate', 'ListingContractDate',
       'BelowGradeFinishedArea', 'BusinessType', 'Latitude.1', 'ListPrice.1',
       'StateOrProvince', 'CoveredSpaces', 'MiddleOrJuniorSchool',
       'FireplaceYN', 'Stories', 'HighSchool', 'Levels', 'ListAgentLastName.1',
       'CloseDate.1', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'BuyerOfficeName.1', 'AssociationFee', 'LotSizeSquareFeet',
       'MiddleOrJuniorSchoolDistrict', 'UnparsedAddress.1', 'Year'],
      dtype='str')

In [5]:
df_listing.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,ListPrice.1,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,Year
count,8.504440e+05,8.537540e+05,2.330590e+05,741807.000000,742511.000000,7.472800e+05,8.516190e+05,853754.000000,0.0,0.0,...,8.516190e+05,0.0,632274.000000,7.759610e+05,394762.000000,691651.000000,577819.000000,7.748880e+05,0.0,853754.000000
mean,1.051204e+06,1.105018e+09,7.814101e+05,34.519429,-118.364684,3.159316e+03,9.842293e+05,19.143911,NaN,NaN,...,9.842293e+05,NaN,1.367686,6.701564e+04,1.933375,1.756404,205.309153,5.639408e+05,NaN,2024.675081
std,6.389884e+06,2.997089e+07,3.457756e+06,1.885437,3.884846,1.051825e+06,2.167942e+06,28.847418,NaN,NaN,...,2.167942e+06,NaN,0.482176,2.421267e+06,5.600222,3.940578,2060.895511,2.313046e+07,NaN,0.684747
min,0.000000e+00,4.216549e+08,0.000000e+00,-117.472493,-159.523315,0.000000e+00,0.000000e+00,-58.000000,NaN,NaN,...,0.000000e+00,NaN,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,NaN,2024.000000
25%,8.500000e+04,1.077489e+09,5.000000e+03,33.757746,-118.517146,1.182000e+03,8.500000e+04,4.000000,NaN,NaN,...,8.500000e+04,NaN,1.000000,4.936000e+03,1.000000,1.000000,0.000000,5.227000e+03,NaN,2024.000000
50%,6.399000e+05,1.104373e+09,5.655000e+05,34.051480,-118.091465,1.601000e+03,6.350000e+05,10.000000,NaN,NaN,...,6.350000e+05,NaN,1.000000,7.227000e+03,2.000000,2.000000,0.000000,7.500000e+03,NaN,2025.000000
75%,1.150000e+06,1.127476e+09,1.025000e+06,34.302492,-117.289035,2.236000e+03,1.150000e+06,22.000000,NaN,NaN,...,1.150000e+06,NaN,2.000000,1.368900e+04,3.000000,2.000000,311.000000,1.655300e+04,NaN,2025.000000
max,1.390000e+09,1.156493e+09,8.200000e+08,737.000000,392.000000,9.090909e+08,4.436503e+08,2539.000000,NaN,NaN,...,4.436503e+08,NaN,2.000000,9.187423e+08,3333.000000,600.000000,968348.000000,7.638115e+09,NaN,2026.000000

### Closed/Sold Properties

In [6]:
df_sold = pd.read_csv("../data/Sold/sold_transactions.csv", encoding="ISO-8859-1")

C:\Users\mayab\AppData\Local\Temp\ipykernel_11692\3090260199.py:1: DtypeWarning: Columns (0: BuyerAgentAOR, 1: ListAgentAOR, 2: WaterfrontYN, 3: ListAgentEmail, 4: OriginatingSystemName, 5: OriginatingSystemSubName, 6: BuyerAgencyCompensationType, 7: latfilled, 8: lonfilled) have mixed types. Specify dtype option on import or set low_memory=False.
  df_sold = pd.read_csv("../data/Sold/sold_transactions.csv", encoding="ISO-8859-1")

In [7]:
df_sold.head()

,BuyerAgentAOR,ListAgentAOR,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,...,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,OriginatingSystemName,OriginatingSystemSubName,BuyerAgencyCompensationType,BuyerAgencyCompensation,latfilled,lonfilled,Year
0,Mlslistings,Mlslistings,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,...,6472.0,NaN,NaN,CRMLS,CRMLS_MLSL,NaN,NaN,NaN,NaN,2024
1,HighDesert,HighDesert,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,...,NaN,52320.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2024
2,OrangeCounty,OrangeCounty,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,...,NaN,217364.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2024
3,InlandValleys,InlandValleys,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,...,NaN,217800.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2024
4,SouthwestRiversideCounty,SouthwestRiversideCounty,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,...,0.0,108883.0,NaN,CRMLS,CRMLS_CRM,NaN,NaN,NaN,NaN,2024

In [8]:
df_sold.columns

Index(['BuyerAgentAOR', 'ListAgentAOR', 'Flooring', 'ViewYN', 'WaterfrontYN',
       'BasementYN', 'PoolPrivateYN', 'OriginalListPrice', 'ListingKey',
       'ListAgentEmail', 'CloseDate', 'ClosePrice', 'ListAgentFirstName',
       'ListAgentLastName', 'Latitude', 'Longitude', 'UnparsedAddress',
       'PropertyType', 'LivingArea', 'ListPrice', 'DaysOnMarket',
       'ListOfficeName', 'BuyerOfficeName', 'CoListOfficeName',
       'ListAgentFullName', 'CoListAgentFirstName', 'CoListAgentLastName',
       'BuyerAgentMlsId', 'BuyerAgentFirstName', 'BuyerAgentLastName',
       'FireplacesTotal', 'AssociationFeeFrequency', 'AboveGradeFinishedArea',
       'ListingKeyNumeric', 'MLSAreaMajor', 'TaxAnnualAmount',
       'CountyOrParish', 'MlsStatus', 'ElementarySchool', 'AttachedGarageYN',
       'ParkingTotal', 'BuilderName', 'PropertySubType', 'LotSizeAcres',
       'SubdivisionName', 'BuyerOfficeAOR', 'YearBuilt', 'StreetNumberNumeric',
       'ListingId', 'BathroomsTotalInteger', 'City', 'TaxYear',
       'BuildingAreaTotal', 'BedroomsTotal', 'ContractStatusChangeDate',
       'ElementarySchoolDistrict', 'CoBuyerAgentFirstName',
       'PurchaseContractDate', 'ListingContractDate', 'BelowGradeFinishedArea',
       'BusinessType', 'StateOrProvince', 'CoveredSpaces',
       'MiddleOrJuniorSchool', 'FireplaceYN', 'Stories', 'HighSchool',
       'Levels', 'LotSizeDimensions', 'LotSizeArea', 'MainLevelBedrooms',
       'NewConstructionYN', 'GarageSpaces', 'HighSchoolDistrict', 'PostalCode',
       'AssociationFee', 'LotSizeSquareFeet', 'MiddleOrJuniorSchoolDistrict',
       'OriginatingSystemName', 'OriginatingSystemSubName',
       'BuyerAgencyCompensationType', 'BuyerAgencyCompensation', 'latfilled',
       'lonfilled', 'Year'],
      dtype='str')

In [9]:
df_sold.describe()

,OriginalListPrice,ListingKey,ClosePrice,Latitude,Longitude,LivingArea,ListPrice,DaysOnMarket,FireplacesTotal,AboveGradeFinishedArea,...,CoveredSpaces,Stories,LotSizeArea,MainLevelBedrooms,GarageSpaces,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,BuyerAgencyCompensation,Year
count,5.894040e+05,5.911150e+05,5.911080e+05,572099.000000,572271.000000,5.493900e+05,5.902050e+05,591115.000000,0.0,0.0,...,0.0,472790.000000,5.370190e+05,313628.000000,515444.000000,407881.000000,5.365620e+05,0.0,67780.000000,591115.000000
mean,9.061188e+05,1.095901e+09,8.745653e+05,34.527335,-118.451190,3.497121e+03,8.400098e+05,43.284872,NaN,NaN,...,NaN,1.364917,4.816426e+04,1.931129,1.765989,185.361762,4.701266e+05,NaN,194.406143,2024.638021
std,5.745172e+06,3.325868e+07,5.275319e+06,1.614966,3.113572,1.226711e+06,1.275660e+06,69.834015,NaN,NaN,...,NaN,0.481407,2.238128e+06,6.252060,3.877687,1633.569593,2.078100e+07,NaN,2152.716451,0.654942
min,0.000000e+00,4.214490e+08,0.000000e+00,-117.472493,-177.646696,0.000000e+00,0.000000e+00,-288.000000,NaN,NaN,...,NaN,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,NaN,0.000000,2024.000000
25%,6.500000e+04,1.075086e+09,5.250000e+04,33.739575,-118.538037,1.183000e+03,6.250000e+04,9.000000,NaN,NaN,...,NaN,1.000000,4.941000e+03,1.000000,1.000000,0.000000,5.186000e+03,NaN,2.000000,2024.000000
50%,6.399900e+05,1.095288e+09,6.299000e+05,34.038490,-118.043184,1.579000e+03,6.299000e+05,22.000000,NaN,NaN,...,NaN,1.000000,7.025000e+03,2.000000,2.000000,0.000000,7.292000e+03,NaN,2.500000,2025.000000
75%,1.089000e+06,1.117368e+09,1.070000e+06,34.304213,-117.329015,2.150000e+03,1.050000e+06,54.000000,NaN,NaN,...,NaN,2.000000,1.148000e+04,3.000000,2.000000,295.000000,1.295800e+04,NaN,2.500000,2025.000000
max,1.390000e+09,1.156473e+09,9.895000e+08,157.000000,329.000000,9.090909e+08,1.375000e+08,12430.000000,NaN,NaN,...,NaN,2.000000,9.187423e+08,3333.000000,600.000000,750000.000000,5.193920e+09,NaN,100000.000000,2026.000000